### ISSUE TITLE
Please update the image to use Libreoffice ^V24.2.0.2 

### ISSUE THREAD

**Issue by SchlauFuchs** [jodconverter/docker-image-jodconverter-runtime#3]
Hi,

We have a problem converting tiff images to PDF with jodconverter due to a bug (lacking feature) in LibreOffice, that has been reported to be fixed since release 24.2.0.2 (https://bugs.documentfoundation.org/show_bug.cgi?id=155444)

Please update libreoffice on this container.

**Comment by EugenMayer** [comment]
Released https://github.com/jodconverter/docker-image-jodconverter-runtime/releases/tag/0.1.8

**Comment by SchlauFuchs** [comment]
Hi, Eugen,

I checked the latest jodconverter image on the repo and it still uses an outdated version of libreoffice:
![image](https://github.com/jodconverter/docker-image-jodconverter-runtime/assets/962205/ce99ec9c-7799-4ea0-968f-7fe2c231d748)
to use version 24 instead of 7.4 you might need to do steps as described in https://libre-software.net/linux/how-to-install-libreoffice-on-ubuntu-linux-mint/ 
```
sudo add-apt-repository ppa:libreoffice/ppa
sudo apt update
sudo apt upgrade
```

**Comment by SchlauFuchs** [comment]
I was playing a bit around, to get the latest libreoffice installed I needed to create a `sources.list` file in `/etc/apt/sources.list.d` with the line
```
deb http://deb.debian.org/debian bookworm-backports main
```
followed by 
`apt update` and ` apt install -t bookworm-backports libreoffice`

this installed `libreoffice (4:24.2.0-1~bpo12+1)`

**Comment by EugenMayer** [comment]
I will not go forward and switch to backports or any other frankendebian variant to upgrade libreoffice - this runtime should be the stable baseline, not an experimental spearhead.

This said, surely i understand your need, so i would suggest what ever project you actually build uppon the runtime

1. your won project / jodconverter solution
2. something based on https://github.com/EugenMayer/officeconverter

In case 1, just install the libreoffice version of your liking during the app-packing step.
In case 2, create your own image based on the published version and upgrade the libre-office variant.

Both are viable and do not need you to fork and maintain all the things, thus i think those are viable solutions in this case.
